"""Multi-tenant Built-in Tool Registry.

Manages available internal function tools. Skills reference tool names
from this registry — tool schemas are auto-generated by Pydantic AI from
the Python function's type hints and docstrings.

This means tool definitions exist in exactly ONE place (here + tools.py),
never duplicated in SKILL.md files.
"""

from __future__ import annotations

import logging
from collections.abc import Callable
from typing import Any

from app.agents import tools

logger = logging.getLogger(__name__)


class BuiltInToolRegistry:
    """Registry for all safe, built-in python function tools.

    Usage::

        # Get a list of resolved tool functions for the agent
        tool_fns = BuiltInToolRegistry.get_tools("app123", ["search_documents", "rank_documents"])
    """

    # Map of tool names to their implementations.
    # Pydantic AI auto-extracts schema from type hints + docstrings.
    # Skill system tools (activate_skill, load_skill_references) are intentionally
    # NOT here — they are registered by SkillsCapability.get_toolset() instead.
    _all_tools: dict[str, Callable[..., Any]] = {
        # Domain tools (RAG operations)
        "search_documents": tools.search_documents_tool,
        "rank_documents": tools.rank_documents_tool,
        "decompose_question": tools.decompose_question_tool,
        "analyze_section": tools.analyze_section_tool,
        "plan_and_reason": tools.plan_and_reason_tool,
        "get_user_classification": tools.get_user_classification_tool,
    }

    @classmethod
    def get_tools(
        cls, application_id: str, allowed_tool_names: list[str]
    ) -> list[Callable[..., Any]]:
        """Return a list of tool functions for the given names.

        These are passed directly to ``Agent(tools=[...])``.
        Pydantic AI auto-generates the function-calling schema from
        each function's signature.

        Args:
            application_id: Tenant ID for logging.
            allowed_tool_names: List of tool names to resolve.

        Returns:
            List of callable tool functions.
        """
        resolved: list[Callable[..., Any]] = []

        logger.info(
            f"[{application_id}] Resolving built-in tools: {allowed_tool_names}"
        )

        for name in allowed_tool_names:
            if name in cls._all_tools:
                resolved.append(cls._all_tools[name])
            else:
                logger.warning(
                    f"[{application_id}] Tool '{name}' not found in registry. "
                    "Skipping."
                )

        return resolved

    @classmethod
    def get_all_tool_names(cls) -> list[str]:
        """Return all registered tool names (for introspection)."""
        return list(cls._all_tools)

    @classmethod
    def register_tool(cls, name: str, func: Callable[..., Any]) -> None:
        """Dynamically register a new tool at runtime.

        Useful for plugins or test fixtures.
        """
        cls._all_tools[name] = func
        logger.info(f"Registered new tool: {name}")
